# Generated by Django 4.1.7 on 2023-04-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_description',
            new_name='receipe_discription',
        ),
    ]
